anagram: implement exercise
exercism/unison pull request #93
Opened 2023-05-20 18:18 UTC by dreig

2023-05-24 07:03 UTC, rlmark commented
This one I can't re-open because the branch was "force pushed or recreated" according to github. 🤔 Digging into this a bit, I found some steps [here](https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c) to try.

2023-05-24 07:23 UTC, dreig commented
I've followed the first 3 steps from that gist/guide, and force pushed the commit with which I opened this PR in the first place. I think it should be possible to re-open this now.

2024-08-06 13:18 UTC, SimaDovakin requested changes

2024-08-06 13:18 UTC, SimaDovakin commented on config.json
> +        "difficulty": 1
More appropriate difficulty is 2 or 3 I guess. Could you set the difficulty to 3, please?

2024-08-06 13:18 UTC, SimaDovakin commented on exercises/practice/anagram/anagram.test.u
> +anagram.test.ex14 = let
This test case should be removed too.

2024-08-06 13:18 UTC, SimaDovakin commented on exercises/practice/anagram/anagram.test.u
> +anagram.test.ex18 = let
And this should also be removed.

2024-08-06 13:20 UTC, SimaDovakin commented
@dreig In addition, could you resolve conflicts in `config.json`? If all tests will pass I'll merge this PR.

2024-08-07 10:39 UTC, dreig commented
sorry, I haven't touched unison since #12in23, and I don't have the time to get back into it and update the PR anytime soon.
Feel free to close this PR and use the source code, if it's in any way useful. I don't care for attribution.

2024-08-07 11:06 UTC, SimaDovakin commented
@dreig Ok. Thanks.

2024-08-08 14:40 UTC, SimaDovakin commented
I transferred this to https://github.com/exercism/unison/pull/138.

2024-08-08 14:40 UTC, closed without merging